### ISSUE TITLE
Not recognizing GameYob as installed.

### ISSUE THREAD

**Issue by Boured** [Wolvan/Homebr3w#16] opened 2016-08-13 23:30 UTC
This isn't much of an issue with the app as it is with detecting whether GameYob is installed or not. This isn't an issue with me just being a noob as when I reinstalled GameYob from Homebr3w and it finished it showed up as green like normal. But when I go back in it registers as being not installed, it installs it just fine but it just thinks that GameYob isn't installed even when it is.

Just thought I would tell this to you guys as it's a little weird bug, and it might happen for other apps as well.

**Comment by Wolvan** [comment] 2016-08-13 23:44
I can reproduce the problem: Seems to be that GameYob actually has a different TID when it is installed compared to what is listed on TitleDB

If you check FBI, GameYob's TID is `000400000F800300` once it is installed
TitleDB has GameYob listed as `0004000000192700`

@ksanislo do you know what the problem here might be?

**Comment by ksanislo** [comment] 2016-08-14 01:43
So, it seems that Steveice10 re-released a new build of this with a new titleid, under the same release version as it had already been indexed. Since the github rescan sees a release it already knew, it didn't bother to collect the file information again.

I'll see if I can use another field inside the release JSON that will give me a more definitely view of if it has really changed or not. It should be avoidable in the future.

**Comment by Wolvan** [comment] 2016-08-14 04:20
I see you fixed the entry in the database, thanks. Can close this issue in that case.

I also checked the `.json` the github API gives back for a release page, why not compare `created_at` and `updated_at` properties each file entry has?

**Closed as completed** 2016-08-14 04:20 UTC
Labels: Won't fix, TitleID/TitleDB Issues
