### ISSUE TITLE
Error when "Checking for updates"

### ISSUE THREAD

**Issue by shadowninja108** [Wolvan/Homebr3w#28] opened 2016-12-07 04:55 UTC
![image](https://cloud.githubusercontent.com/assets/13044396/20955154/267b1592-bbfe-11e6-9805-aad573fd4772.png)
When init of the CIA version, it shows this error slightly after "Checking for updates". The data and time are set correctly (might be a minute off). Not sure what other variables  I can list.

**Comment by Wolvan** [comment] 2016-12-07 08:51
This seems to be a problem with TitleDB right now, if you go to https://api.titledb.com/v0/ it should give you an app list in json format but it only gives error 502 Bad Gateway for me.

@ksanislo did you break something?

**Comment by ksanislo** [comment] 2016-12-07 15:04
Looks like the new WSGI backend ran the server out of memory and it started
OOM-killing processes. I've got a bug that is forcing me to keep titledb
running in debug mode for the moment actually, which is most likely a big
part of the problem. If I can't find a solution soon I'm going to have to
switch back to the v0 codebase until I can figure out why running under
production settings is causing database transaction problems that don't
appear when set as devel.

Anyway, it should be back for now. Sorry about the downtime.

**Comment by Wolvan** [comment] 2016-12-07 19:18
Thx k, good to know

**Comment by Wolvan** [comment] 2016-12-07 22:36
Just checked, now the site doesn't send a reply at all it seems
Edit:
Nvm, all of a sudden it works

**Comment by ksanislo** [comment] 2016-12-07 23:13
I've rolled back to the v0 code... I don't have time to troubleshoot the db locking issue at the moment, so I'll let the old stuff run a few more days until I can figure out the real root cause.

**Comment by Wolvan** [comment] 2016-12-11 14:39
Closing this since it seems fixed

**Closed as completed by Wolvan** 2016-12-11 14:39 UTC
Labels: Won't fix, Priority: High, TitleID/TitleDB Issues
